#!/bin/bash

#PBS -S /bin/bash
#PBS -l select=1:ncpus=28,walltime=24:00:00
#PBS -j oe
#PBS -N presm_kmeans

FILENAME="main_presmoothdf_kmeans_noout"

cd "${PBS_O_WORKDIR}"

# clean log
rm -f log_presmooth_kmeans.txt compile_presmooth_kmeans.txt
echo "cleaning log files..." >> log_presmooth_kmeans.txt

# init spack
echo "loading spack" >> log_presmooth_kmeans.txt
if [ ! -f "${HOME}/spack.sh" ]; then
    echo "spack configuration file not found" >> log_presmooth_kmeans.txt
    exit 1
fi
source "${HOME}/spack.sh" >> log_presmooth_kmeans.txt 2>&1

echo "loading fdapde_devel environment" >> log_presmooth_kmeans.txt
spack env activate fdapde_devel >> log_presmooth_kmeans.txt 2>&1

# check packages
EIGEN_LOC="$(spack location -i eigen)"
if [ -z "$EIGEN_LOC" ]; then
    echo "Eigen dependency not found" >> log_presmooth_kmeans.txt
    exit 1
fi
echo "Eigen library found at ${EIGEN_LOC}" >> log_presmooth_kmeans.txt

# compile
echo "compiling..." >> log_presmooth_kmeans.txt
g++ -o $FILENAME $FILENAME.cpp \
    -I./fdaPDE-cpp \
    -I./fdaPDE-cpp/fdaPDE/core \
    -I"$EIGEN_LOC/include/eigen3" \
    -march=native -O2 -std=c++20 >> compile_presmooth_kmeans.txt 2>&1

# run
echo "launching executable..." >> log_presmooth_kmeans.txt
./$FILENAME >> log_presmooth_kmeans.txt
