#!/bin/bash

#PBS -S /bin/bash
#PBS -l select=1:ncpus=28,walltime=24:00:00
#PBS -j oe
#PBS -N reK_st_50piuvicini

FILENAME="main_jb_st_50piuvicini"

cd "${PBS_O_WORKDIR}"

# clean log
rm -f logv.txt compilev.txt
echo "cleaning log files..." >> logv.txt

# init spack
echo "loading spack" >> logv.txt
if [ ! -f "${HOME}/spack.sh" ]; then
    echo "spack configuration file not found" >> logv.txt
    exit 1
fi
source "${HOME}/spack.sh" >> logv.txt 2>&1

echo "loading fdapde_devel environment" >> logv.txt
spack env activate fdapde_devel >> logv.txt 2>&1

# check packages
EIGEN_LOC="$(spack location -i eigen)"
if [ -z "$EIGEN_LOC" ]; then
    echo "Eigen dependency not found" >> logv.txt
    exit 1
fi
echo "Eigen library found at ${EIGEN_LOC}" >> logv.txt

# compile
echo "compiling..." >> logv.txt
g++ -o $FILENAME $FILENAME.cpp \
    -I./fdaPDE-cpp \
    -I./fdaPDE-cpp/fdaPDE/core \
    -I"$EIGEN_LOC/include/eigen3" \
    -march=native -O2 -std=c++20 >> compilev.txt 2>&1

# run
echo "launching executable..." >> logv.txt
./$FILENAME >> logv.txt 2>&1
