#!/bin/bash

#PBS -S /bin/bash
#PBS -l select=1:ncpus=28,walltime=24:00:00
#PBS -j oe
#PBS -N kmulti_vicini

FILENAME="src_vicini/main_kmeans_multi"

cd "${PBS_O_WORKDIR}"

# clean log
rm -f logk.txt compilek.txt
echo "cleaning log files..." >> logk.txt

# init spack
echo "loading spack" >> logk.txt
if [ ! -f "${HOME}/spack.sh" ]; then
    echo "spack configuration file not found" >> logk.txt
    exit 1
fi
source "${HOME}/spack.sh" >> logk.txt 2>&1

echo "loading fdapde_devel environment" >> logk.txt
spack env activate fdapde_devel >> logk.txt 2>&1

# check packages
EIGEN_LOC="$(spack location -i eigen)"
if [ -z "$EIGEN_LOC" ]; then
    echo "Eigen dependency not found" >> logk.txt
    exit 1
fi
echo "Eigen library found at ${EIGEN_LOC}" >> logk.txt

# compile
echo "compiling..." >> logk.txt
g++ -o $FILENAME $FILENAME.cpp \
    -I../application/fdaPDE-cpp \
    -I../application/fdaPDE-cpp/fdaPDE/core \
    -I"$EIGEN_LOC/include/eigen3" \
    -march=native -O2 -std=c++20 >> compilek.txt 2>&1

# run
echo "launching executable..." >> logk.txt
./$FILENAME >> logk.txt 2>&1
