#!/bin/bash

#PBS -S /bin/bash
#PBS -l select=1:ncpus=28,walltime=24:00:00
#PBS -j oe
#PBS -N presmooth_df1e81e7

FILENAME="src_vicini/main_presmooth_df_1e81e7"
FILENAME_exe="src_vicini/main_presmooth_df_1e81e7"

cd "${PBS_O_WORKDIR}"

# clean log
rm -f log_pdf1e81e7.txt compile_pdf1e81e7.txt
echo "cleaning log files..." >> log_pdf1e81e7.txt

# init spack
echo "loading spack" >> log_pdf1e81e7.txt
if [ ! -f "${HOME}/spack.sh" ]; then
    echo "spack configuration file not found" >> log_pdf1e81e7.txt
    exit 1
fi
source "${HOME}/spack.sh" >> log_pdf1e81e7.txt 2>&1

echo "loading fdapde_devel environment" >> log_pdf1e81e7.txt
spack env activate fdapde_devel >> log_pdf1e81e7.txt 2>&1

# check packages
EIGEN_LOC="$(spack location -i eigen)"
if [ -z "$EIGEN_LOC" ]; then
    echo "Eigen dependency not found" >> log_pdf1e81e7.txt
    exit 1
fi
echo "Eigen library found at ${EIGEN_LOC}" >> log_pdf1e81e7.txt

# compile
echo "compiling..." >> log_pdf1e81e7.txt
g++ -o $FILENAME_exe $FILENAME.cpp \
    -I../application/fdaPDE-cpp \
    -I../application/fdaPDE-cpp/fdaPDE/core \
    -I"$EIGEN_LOC/include/eigen3" \
    -march=native -O2 -std=c++20 >> compile_pdf1e81e7.txt 2>&1

# run
echo "launching executable..." >> log_pdf1e81e7.txt
./$FILENAME_exe >> log_pdf1e81e7.txt 2>&1
